kind: template
load: build.yaml
data:
  builds:
  - image_name: linux-x64
  - image_name: linux-x86
  - image_name: linux-mipsel-lts
  - image_name: linux-mips-lts
  - image_name: linux-armv7-lts
  - image_name: linux-armv6-lts
  - image_name: linux-armv5
  - image_name: linux-armv5-musl
  - image_name: linux-arm64-lts
