kind: pipeline
type: docker
name: default
steps:
  - name: build
    image: xwtkdym/ubuntu:ci
    commands:
      - ls -alh
      - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install
      - cmake --build build --config Debug -- -j `nproc`
      - cmake --build build --config Debug --target install