kind: template
load: build.yaml
data:
  builds:
  - image_name: linux-x64
    build_types:
      - Debug
      - Release
  - image_name: linux-x86
    build_types:
      - Debug
      - Release
  - image_name: linux-mipsel-lts
    build_types:
      - Debug
      - Release
  - image_name: linux-mips-lts
    build_types:
      - Debug
      - Release
  - image_name: linux-armv7-lts
    build_types:
      - Debug
      - Release
  - image_name: linux-armv6-lts
    build_types:
      - Debug
      - Release
  - image_name: linux-armv5-lts
    build_types:
      - Debug
      - Release
  - image_name: linux-arm64-lts
    build_types:
      - Debug
      - Release
