kind: pipeline
type: docker
name: default

steps:
  - name: configure
    image: dockcross/linux-x64
    pull: if-not-exists
    commands:
      - cmake . -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
trigger:
  ref:
    - refs/heads/develop
    - refs/heads/master
    - refs/tags/**
    - refs/pull/**
