#set(CMAKE_SYSTEM_NAME Linux)
#set(CMAKE_SYSTEM_PROCESSOR x86_64)
#set(CMAKE_HOST_SYSTEM x86_64)
#set(CMAKE_C_COMPILER_LAUNCHER "/usr/bin/afl-clang-fast")
#set(CMAKE_CXX_COMPILER_LAUNCHER "/usr/bin/afl-clang-fast++")
#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti -fsanitize=address,undefined -fno-sanitize-recover=all -g")
#set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fno-rtti -fsanitize=address,undefined -fno-sanitize-recover=all -g")
#set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fno-rtti -fsanitize=address,undefined -fno-sanitize-recover=all")
#set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} -fno-rtti -fsanitize=address,undefined -fno-sanitize-recover=all")
