kind: pipeline
type: docker
name: default
steps:
  - name: build {{ .input.image_name }}
    image: dockcross/{{ .input.image_name }}
    commands:
    {{ range .input.build }}
    - cmake . -Bbuild-{{.arch}} -DCMAKE_BUILD_TYPE={{.type}}
    - cmake --build build-{.arch} --config={{.type}} -- -j`nproc`
    {{ end }}