kind: pipeline
type: docker
name: default
steps:
  {{ range .input.builds }}
  {{ $image_name := .image_name }}
  - name: build {{ .image_name }}
    image: dockcross/{{ .image_name }}
    commands:
    {{ if .build_types }}
        {{ $build_types := .build_types }}
    {{ else }}
        {{ $build_types := list Debug Release }}
    {{ end }}
    {{ range $build_types }}
    - cmake . -Bbuild-{{$image_name}}-{{.}} -DCMAKE_BUILD_TYPE={{.}}
    - cmake --build build-{{$image_name}}-{{.}} --config={{.}} -- -j`nproc`
    {{end}}
  {{ end }}

  - name: list all build dir
    image: alpine
    commands:
      - ls -l build-*