#ifndef ULIB_SRC_ULIB_BASE_STRINGIZE_MACROS_H_
#define ULIB_SRC_ULIB_BASE_STRINGIZE_MACROS_H_

#define STRINGIZE_NO_EXPANSION(x) #x

#define STRINGIZE STRINGIZE_NO_EXPANSION(x)

#endif// ULIB_SRC_ULIB_BASE_STRINGIZE_MACROS_H_
