name: linux-x64-gcc
on:
  - push
  - pull_request
concurrency:
  group: linux-x64-gcc-${{ github.ref }}
  cancel-in-progress: true
permissions:
  - read

jobs:
  linux-gcc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: update
        runs: sudo apt-get update

      - name: configure
        runs: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DULIB_BUILD_TESTS=ON
      - name: build
        runs: |
          cmake --build build -j `nproc`
      - name: test
        runs: |
          cd build && ctest --output-on-failure -j `nproc`

      - name: configure-shared
        runs: |
          mkdir build-shared && cd build-shared
          cmake .. -DCMAKE_BUILD_TYPE=Release -DULIB_BUILD_TESTS=ON -DULIB_SHARED_LIB=ON
      - name: build-shared
        runs: |
          cmake --build build-shared -j `nproc`
      - name: test-shared
        runs: |
          cd build-shared && ctest --output-on-failure -j `nproc`